/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Edimar
 */
public class TelaEntrada extends javax.swing.JFrame {

    /**
     * Creates new form TelaEntrada
     */
    public TelaEntrada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cx_estoque = new javax.swing.JTextField();
        cx_nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cx_codigo1 = new javax.swing.JTextField();
        btnVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cx_tabela = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        cx_codigo2 = new javax.swing.JTextField();
        btn_pequisa1 = new javax.swing.JButton();
        btnPequisa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(84, 84, 84));
        jPanel1.setForeground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(null);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Quantidade da Entrada :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 380, 200, 19);
        jPanel1.add(cx_estoque);
        cx_estoque.setBounds(40, 150, 660, 30);
        jPanel1.add(cx_nome);
        cx_nome.setBounds(140, 80, 560, 30);

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/INVENTORY cinza escuro.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(300, 20, 150, 150);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nome:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(140, 50, 44, 19);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("código:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 50, 60, 19);
        jPanel1.add(cx_codigo1);
        cx_codigo1.setBounds(50, 410, 170, 30);

        btnVoltar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-desfazer-48.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(btnVoltar);
        btnVoltar.setBounds(580, 410, 110, 30);

        cx_tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Estoque"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(cx_tabela);
        if (cx_tabela.getColumnModel().getColumnCount() > 0) {
            cx_tabela.getColumnModel().getColumn(1).setPreferredWidth(400);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 240, 660, 110);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Código de barras: ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 120, 140, 19);
        jPanel1.add(cx_codigo2);
        cx_codigo2.setBounds(40, 80, 80, 30);

        btn_pequisa1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_pequisa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-pesquisar-48.png"))); // NOI18N
        btn_pequisa1.setText("Pesquisar");
        jPanel1.add(btn_pequisa1);
        btn_pequisa1.setBounds(320, 200, 120, 30);

        btnPequisa.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnPequisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-adicionar-48.png"))); // NOI18N
        btnPequisa.setText("Adicionar");
        jPanel1.add(btnPequisa);
        btnPequisa.setBounds(240, 410, 120, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 750, 500);

        setSize(new java.awt.Dimension(766, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
     TelaMenu t1 = new TelaMenu();
     t1.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEntrada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPequisa;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JButton btn_pequisa1;
    private javax.swing.JTextField cx_codigo1;
    private javax.swing.JTextField cx_codigo2;
    private javax.swing.JTextField cx_estoque;
    private javax.swing.JTextField cx_nome;
    private javax.swing.JTable cx_tabela;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
